name: Build and deploy Node.js app to Azure Web App - FaceNLaernMVP

on:
  push:
    branches:
      - Deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: Anexos/create-react-app/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('Anexos/create-react-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      

      - name: npm install, build, and test in React app directory
        run: |
          cd Anexos/create-react-app
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r build.zip ./build/* 
        working-directory: Anexos/create-react-app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: Anexos/create-react-app/build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip build.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FaceNLaernMVP'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6BE4167D75A248788D56C41F8BE5273F }}
